version: '3.8'

services:
  # --- THE APPS ---
  app1:
    build: ./app
    hostname: "instance-01"
    restart: always
    ports:
      - "5001:5000" # Expose for metrics debugging

  app2:
    build: ./app
    hostname: "instance-02"
    restart: always
    ports:
      - "5002:5000"

  # --- LOAD BALANCER ---
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2

  # --- ðŸ“Š PROMETHEUS (The Recorder) ---
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # --- ðŸ“ˆ GRAFANA (The Dashboard) ---
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus